WIP: Add custom shader option
f3d-app/f3d pull request #1474
Opened 2024-06-18 19:29 UTC by Meakk

2024-06-19 15:06 UTC, Meakk commented
@mwestphal I will make the doc more clear but it's pretty much ready for a first pass of review.

2024-06-19 15:41 UTC, mwestphal commented on _config.yml
> +      path: "doc/libf3d/CUSTOM_SHADER.md"
if exposed in the F3D app, it should be documented in the user doc.

2024-06-19 15:42 UTC, mwestphal commented on vtkext/private/module/vtkF3DUserRenderPass.cxx
> +    return;
can this happen ? if not, assert instead ?

2024-06-19 15:42 UTC, mwestphal commented on vtkext/private/module/vtkF3DUserRenderPass.h
> +  std::string UserShader;
put all these members as private, no reason to be protected.

2024-06-19 15:44 UTC, mwestphal commented on vtkext/private/module/vtkF3DUserRenderPass.cxx
> +    this->QuadHelper = nullptr;
can this happen ? add a VTK test to cover it ?

2024-06-20 18:12 UTC, mwestphal commented on _config.yml
> +      path: "doc/libf3d/FINAL_SHADER.md"
wrong location

2024-06-20 18:12 UTC, mwestphal commented on application/testing/CMakeLists.txt
> +# Test opening a directory
wrong comment

2024-06-20 18:17 UTC, mwestphal commented on doc/user/FINAL_SHADER.md
> +f3d model.obj --final-shader "$(cat final.glsl)"
thinking about it I'd rather have the first example to be something cross platform

2024-06-20 18:18 UTC, mwestphal commented on vtkext/private/module/vtkF3DUserRenderPass.cxx
> +    return;
unreachable ?

2024-06-20 18:26 UTC, Meakk commented on doc/user/FINAL_SHADER.md
> +f3d model.obj --final-shader "$(cat final.glsl)"
The whole point of this doc is to explain to the user how to use a string with new lines inside.  
I can remove it completely and let the user figure out how to do that, it's very standard after all...

2024-06-20 18:33 UTC, Meakk commented on vtkext/private/module/vtkF3DUserRenderPass.cxx
> +    return;
covered with the new test

2024-06-21 05:41 UTC, mwestphal commented on doc/user/FINAL_SHADER.md
> +f3d model.obj --final-shader "$(cat final.glsl)"
Got it. Mention that this example may not work on Windows at least.

2024-06-22 15:41 UTC, mwestphal approved these changes

2024-06-22 16:46 UTC, mwestphal commented on doc/user/FINAL_SHADER.md
missing from doc/user/README_USER.md

2024-06-22 16:46 UTC, mwestphal requested changes
small doc change

2024-06-24 13:06 UTC, mwestphal approved these changes

2024-06-24 13:24 UTC, merged