Update F3DOptionsTools.cxx
f3d-app/f3d pull request #1644
Opened 2024-10-01 14:18 UTC by brown-eric

Switched the order of checking for unknown and checking for help/version arguments. This ensures that if a user types something like f3d --help --unknown, the help message will be shown rather than just the error about the unknown option.

2024-10-01 14:22 UTC, mwestphal requested changes
- Please add a link to the issue in the description, eg: "Fix #1636 "
 - Please add a test for this behavior in application/testing/CMakeLists.txt, you can look at `TestHelp` for inspiration.

2024-10-01 22:16 UTC, brown-eric commented
Updated by adding testcases for --help or --version before unknown to make sure the code behaves as intended

2024-10-02 06:58 UTC, mwestphal commented on application/testing/CMakeLists.txt
> +f3d_test(NAME TestHelpPrecedenceWithUnknownOption ARGS --help --unknown REGEXP "F3D Command Line Help"  NO_BASELINE)
you may to check for "Usage:" instead, as the `TestHelp` does.

2024-10-02 06:59 UTC, mwestphal commented on application/testing/CMakeLists.txt
> +f3d_test(NAME TestVersionPrecedenceWithUnknownOption ARGS --version --unknown REGEXP "F3D Version" NO_BASELINE)
you may want to check for `Version:` as the `TestVersion` does.

2024-10-02 06:59 UTC, mwestphal requested changes
you can run your test locally to check them :)

2024-10-02 15:49 UTC, mwestphal approved these changes
@snoyer please review

2024-10-02 20:35 UTC, merged