Dump "camera" info should dump information about all options
f3d-app/f3d pull request #1809
Opened 2024-12-19 18:38 UTC by samoncrief

2024-12-21 06:48 UTC, mwestphal requested changes
small changes needed

2024-12-21 06:48 UTC, mwestphal commented on library/private/scene_impl.h
> +  // Display available cameras in the log
please use doxygen style doc

```
/**
 *
 */
 ```

2024-12-21 06:48 UTC, mwestphal commented on library/src/scene_impl.cxx
> +}
this code is a duplicate of `DisplayImporterDescription`, please factorize

2024-12-30 21:23 UTC, Meakk approved these changes

2024-12-31 08:46 UTC, mwestphal approved these changes

2024-12-31 08:47 UTC, merged