Bug fix for segfault iss #1795
f3d-app/f3d pull request #1847
Opened 2024-12-28 18:04 UTC by hant-hub

This fixes a UI related segfault due to a stale observer reference in VTK. This was first found in issue #1795 where a python application segfaults if you delete and recreate the f3d engine.

2024-12-28 18:05 UTC, hant-hub commented
I'm unsure how to generate synthetic vtkWindowEvents for testing, I guess I could make a c++ test for this?

2024-12-28 19:00 UTC, hant-hub commented
For the test there is a thing where I believe due to memory layout issues the segfault is inconsistent. I could only get it to reliably detect the segfault by repeating the test multiple times. Currently I set that to 5 since that almost always catches the bug in my testing, but we might want to change that or install some kind of other memory validation.

2024-12-28 23:42 UTC, hant-hub commented
not really sure why the last two tests are failing, any advice would be appreciated.

2024-12-29 10:54 UTC, Meakk commented on library/testing/CMakeLists.txt
> +configure_file("${F3D_SOURCE_DIR}/testing/recordings/TestSDKEngineRecreation.log.in"
I don't think you need a configure_file, just use a .log file directly

2024-12-29 10:55 UTC, mwestphal commented
> Currently I set that to 5 since that almost always catches the bug in my testing, but we might want to change that or install some kind of other memory validation.

Thats fine, memory issues are like that :)

2024-12-29 10:55 UTC, Meakk commented
> not really sure why the last two tests are failing, any advice would be appreciated.

Not sure about the static analysis error, it seems unrelated.  
About the crash with VTK 9.2.6, I can try to reproduce locally next week.

2024-12-29 10:57 UTC, mwestphal commented
> not really sure why the last two tests are failing, any advice would be appreciated.

VTK v9.2.6: Probably due to an already fixed bug in VTK, just not add the test with VTK 9.2.6 in the CMake logic

static_analysis: I dont get why this would be wrong and definitely not caused by ytour changes , is your branch based on master ?

2024-12-29 10:59 UTC, mwestphal commented on library/testing/TestSDKEngineRecreation.cxx
> +#include <window.h>
not all includes needed

2024-12-29 11:00 UTC, mwestphal requested changes
nice fix! the main change looks good, small changes needed.

2024-12-29 11:27 UTC, snoyer commented
The static analysis error is unrelated but it looks valid, the real question is why is it showing up only now?
```
library/src/interactor_impl.cxx:1049:66: style: Unused variable: doc [unusedVariable]
  std::vector<std::tuple<std::string, std::string, std::string>> doc;
```
https://github.com/f3d-app/f3d/blob/27d1e8a117b978bf830cc7d3a8601827f18309ed/library/src/interactor_impl.cxx#L1041-L1053

2024-12-29 12:10 UTC, mwestphal commented
> The static analysis error is unrelated but it looks valid, the real question is why is it showing up only now?
> 
> ```
> library/src/interactor_impl.cxx:1049:66: style: Unused variable: doc [unusedVariable]
>   std::vector<std::tuple<std::string, std::string, std::string>> doc;
> ```
> 
> https://github.com/f3d-app/f3d/blob/27d1e8a117b978bf830cc7d3a8601827f18309ed/library/src/interactor_impl.cxx#L1041-L1053

Good point, moving this discussion to: https://github.com/f3d-app/f3d/pull/1848

2024-12-29 12:10 UTC, mwestphal commented
> The static analysis error is unrelated but it looks valid, the real question is why is it showing up only now?
> 
> ```
> library/src/interactor_impl.cxx:1049:66: style: Unused variable: doc [unusedVariable]
>   std::vector<std::tuple<std::string, std::string, std::string>> doc;
> ```
> 
> https://github.com/f3d-app/f3d/blob/27d1e8a117b978bf830cc7d3a8601827f18309ed/library/src/interactor_impl.cxx#L1041-L1053

Good point, moving this discussion here:

2024-12-29 12:11 UTC, mwestphal commented
(my bad, I did not intend to do that)

2024-12-29 19:15 UTC, mwestphal commented
Anyway, static_analysis CI is fixed in master @hant-hub

2025-01-02 15:10 UTC, mwestphal approved these changes

2025-01-02 15:10 UTC, mwestphal commented
Nice fix @hant-hub

2025-01-02 15:11 UTC, mwestphal commented
@Meakk wanna review ?

2025-01-02 16:03 UTC, Meakk requested changes
small comment regarding code style.  
Otherwise, it looks good to me

2025-01-02 16:03 UTC, Meakk commented on library/testing/TestSDKEngineRecreation.cxx
> +  }
let's modernize the memory management using unique_ptr's
```suggestion
  auto eng = std::make_unique<f3d::engine>(f3d::engine::create(false));
  eng->getInteractor().start(1 / 30, [eng]() { eng->getInteractor().stop(); });
  eng = nullptr;
  for (int i = 0; i < 5; i++)
  {
    auto eng2 = std::make_unique<f3d::engine>(f3d::engine::create(false));
    eng2->getInteractor().playInteraction(interactionFilePath);
  }
```

2025-01-02 16:29 UTC, snoyer commented on library/testing/TestSDKEngineRecreation.cxx
> +  }
can you scope the first engine too instead of doing `= nullptr`?

2025-01-02 16:31 UTC, Meakk commented on library/testing/TestSDKEngineRecreation.cxx
> +  }
it's possible too. I'm fine with both

2025-01-03 09:20 UTC, Meakk commented on CMakeLists.txt
> +set(CMAKE_EXPORT_COMPILE_COMMANDS true)
Why is it needed? That's an option we usually set in command line when configuring (`-DCMAKE_EXPORT_COMPILE_COMMANDS=ON`) for static analysis tools (clang-tidy/cppcheck)

2025-01-03 09:32 UTC, hant-hub commented on CMakeLists.txt
> +set(CMAKE_EXPORT_COMPILE_COMMANDS true)
Sorry had that there since it made my workflow a bit easier. I can get rid of that.

2025-01-03 09:35 UTC, Meakk approved these changes
Thank you!

2025-01-03 10:05 UTC, merged

2025-01-03 10:06 UTC, mwestphal commented
@hant-hub thanks for your contribution!