Fixup rpaths
f3d-app/f3d pull request #290
Opened 2022-05-18 10:20 UTC by mwestphal

2022-05-18 10:48 UTC, mwestphal commented on library/CMakeLists.txt
> +
this is the fix, wdyt ?

2022-05-18 10:48 UTC, mwestphal commented on library/CMakeLists.txt
> +
@Meakk

2022-05-20 08:44 UTC, Meakk requested changes
You need to set `CMAKE_SKIP_INSTALL_RPATH` in the CI

2022-05-20 12:52 UTC, Meakk approved these changes

2022-05-20 13:01 UTC, merged