Use std::make_unique whenever possible
f3d-app/f3d pull request #340
Opened 2022-08-01 08:09 UTC by mwestphal

2022-08-01 20:52 UTC, Meakk commented
FYI, this is covered by clang-tidy. See https://github.com/f3d-app/f3d/pull/329

2022-08-02 07:43 UTC, mwestphal commented
> FYI, this is covered by clang-tidy. See #329

Ok, but I may merge this before your tidy work :)

2022-08-03 12:42 UTC, Meakk requested changes

2022-08-03 12:42 UTC, Meakk commented on library/public/engine.h
> +#include <memory>
to remove

2022-08-03 12:42 UTC, Meakk commented on library/VTKExtensions/Readers/vtkF3DAssimpImporter.cxx
> +#include <memory>
is it required?

2022-08-03 13:27 UTC, mwestphal commented on library/public/engine.h
> +#include <memory>
no

2022-08-03 13:27 UTC, mwestphal commented on library/VTKExtensions/Readers/vtkF3DAssimpImporter.cxx
> +#include <memory>
yes

2022-08-03 13:39 UTC, Meakk approved these changes

2022-08-03 13:40 UTC, merged