Fix translucent objects when the texture is RGBA
f3d-app/f3d pull request #341
Opened 2022-08-01 20:48 UTC by Meakk

Fix #332

2022-08-02 07:42 UTC, mwestphal commented
please rebase on master and add a `TestTextureColor` test.

2022-08-02 14:25 UTC, mwestphal requested changes
please rebase on master and add a TestTextureColor test.

2022-08-07 08:49 UTC, Meakk commented
Done, please review again @mwestphal

2022-08-07 10:42 UTC, mwestphal commented on cmake/testing.cmake
> +f3d_test(NAME TestTextureColorWithOptions DATA WaterBottle.glb ARGS --geometry-only --texture-base-color=${CMAKE_SOURCE_DIR}/testing/data/albedo_mod.png --color=1,1,0 --depth-peeling DEFAULT_LIGHTS)
maybe something like that:
```
 f3d_test(NAME TestTextureColor DATA WaterBottle.glb ARGS --geometry-only --texture-base-color=${CMAKE_SOURCE_DIR}/testing/data/albedo_mod.png --depth-peeling DEFAULT_LIGHTS)

 f3d_test(NAME TestTextureColorWithOptions DATA WaterBottle.glb ARGS --geometry-only --texture-base-color=${CMAKE_SOURCE_DIR}/testing/data/albedo_mod.png --color=1,1,0 --opacity=0.8 --depth-peeling DEFAULT_LIGHTS)
 ```

2022-08-07 10:43 UTC, mwestphal commented
So the multiplication issue is not fixed ?

2022-08-09 11:03 UTC, Meakk commented
> So the multiplication issue is not fixed ?

Fixed here: https://gitlab.kitware.com/vtk/vtk/-/merge_requests/9467

2022-08-09 19:00 UTC, Meakk commented
The test will be fixed when the VTK MR will be merged

2022-08-17 10:02 UTC, Meakk commented on cmake/testing.cmake
> +if(VTK_VERSION VERSION_GREATER_EQUAL 9.1.202208XX)
```suggestion
if(VTK_VERSION VERSION_GREATER_EQUAL 9.1.20220811)
```

2022-08-17 10:04 UTC, Meakk commented on cmake/testing.cmake
> +if(VTK_VERSION VERSION_GREATER_EQUAL 9.1.20220811)
```suggestion
if(VTK_VERSION VERSION_GREATER_EQUAL 9.2.20220811)
```

2022-08-18 01:49 UTC, mwestphal approved these changes

2022-08-18 01:49 UTC, mwestphal commented
+1

2022-08-18 05:20 UTC, merged