Improve versioning display with `--version`
f3d-app/f3d pull request #818
Opened 2023-05-19 08:12 UTC by mwestphal

- Fix cmake logic to avoid including with full path
 - Use VTK_VERSION_FULL when possible to determine the VTK version to display
 - Rely on git-describe to create a F3D_VERSION_FULL

2023-05-19 08:16 UTC, mwestphal commented
@snoyer please review, F3D will not lie about versions anymore :)

2023-05-19 09:16 UTC, snoyer commented
> @snoyer please review, F3D will not lie about versions anymore :)

Generous of you to assume I know anything about cmake :) but I'm going to sit the review out.

Best I can do is test it...

nightly from sometime last month:
```
> /opt/f3d/bin/f3d --version
F3D 2.0.0

F3D - A fast and minimalist 3D viewer
Version: 2.0.0.
Build date: 2023-04-20 16:41:10.
Build system: Linux 64-bits.
Compiler: GNU 8.4.0.
External rendering module: ON.
Raytracing module: OFF.
VTK version: 9.2.6 (build 20230224).
Copyright (C) 2019-2021 Kitware SAS.
Copyright (C) 2021-2023 Michael Migliore, Mathieu Westphal.
License BSD-3-Clause.
By Michael Migliore, Mathieu Westphal and Joachim Pouderoux.
```

master:
```
make -j8 && bin/f3d --version
...
[100%] Built target f3d
F3D 2.0.0

F3D - A fast and minimalist 3D viewer
Version: 2.0.0.
Build date: 2023-05-19 09:10:57.
Build system: Linux 64-bits.
Compiler: GNU 13.0.1.
External rendering module: OFF.
Raytracing module: OFF.
VTK version: 9.2.5 (build 5).
Copyright (C) 2019-2021 Kitware SAS.
Copyright (C) 2021-2023 Michael Migliore, Mathieu Westphal.
License BSD-3-Clause.
By Michael Migliore, Mathieu Westphal and Joachim Pouderoux.
```

your branch:
```
> make -j8 && bin/f3d --version
CMake Warning at cmake/f3dVersion.cmake:48 (message):
  Version from git (1.3.1) disagrees with hard coded version (2.0.0).  Either
  update the git tags or main CMakeLists.txt.
Call Stack (most recent call first):
  CMakeLists.txt:39 (determine_version)
-- VTK 9.2.5 found
...
[100%] Built target f3d
F3D 1.3.1

F3D - A fast and minimalist 3D viewer
Version: 1.3.1-385-g39a11ba6.
Build date: 2023-05-19 09:01:15.
Build system: Linux 64-bits.
Compiler: GNU 13.1.1.
External rendering module: OFF.
Raytracing module: OFF.
VTK version: 9.2.5.
Copyright (C) 2019-2021 Kitware SAS.
Copyright (C) 2021-2023 Michael Migliore, Mathieu Westphal.
License BSD-3-Clause.
By Michael Migliore, Mathieu Westphal and Joachim Pouderoux.
```

Not super helpful observations:
- `git describe` reports weird stuff but maybe that's because it's a branch and not main? or do I need to explicitly update tags somehow? either way, F3D repeats what git says as intended, the wrong version is probably user error on my side.
- VTK build info got lost somehow?

2023-05-19 10:04 UTC, mwestphal commented
- About the warning in `git describe`. Caused by an issue in the release process. The v2.0.0 tag had not been "annotated" I took care of that but you need to force update your tags locally with `git fetch --tags -f`. This issue will not appear on a fresh clone.

- VTK "build 5" is replaced by "date: 20230519" if it makes sense. In your case, since you are building against VTK 9.2.5 release, no need to add the date as it is a true release.

2023-05-19 10:32 UTC, snoyer commented
All good then :+1:

2023-05-20 09:25 UTC, Meakk requested changes

2023-05-20 09:25 UTC, Meakk commented on CMakeLists.txt
> +
useless additional line

2023-05-20 09:25 UTC, Meakk commented on cmake/f3dVersion.cmake
> +function(determine_version source_dir git_command var_prefix)
Like `f3d_embed_file`, should we prefix the CMake functions in this file by `f3d_`?

2023-05-20 09:25 UTC, Meakk commented on cmake/f3dVersion.cmake
> +  string(REGEX MATCH "^v?(([0-9]+)\\.([0-9]+)\\.([0-9]+)-?(.*))$"
In our case, we are always prefixed by `v`

```suggestion
  string(REGEX MATCH "^v(([0-9]+)\\.([0-9]+)\\.([0-9]+)-?(.*))$"
```

2023-05-20 10:24 UTC, Meakk approved these changes

2023-05-20 10:24 UTC, merged