Add Ortographic View
f3d-app/f3d pull request #924
Opened 2023-07-21 20:49 UTC by lknknm

As suggested on the Issue #885, this PR has the intention to continue developing the camera hotkeys feature.
This will implement the Ortographic View bound to the `5` key of the keyboard/numeric keyboard, using the `vtkCamera::ParallelProjectionOn/Off()` methods.

2023-07-21 21:41 UTC, Meakk requested changes
Please add the Python bindings. You don't have to add the Java and JS bindings tho, except if you really want :)  
You also need tests in both C++ and Python since you are extending the public API.  
An interactive test (with `add_test`) is also required.

2023-07-21 21:41 UTC, Meakk commented on library/private/camera_impl.h
> +  camera& ortoview() override;
English is not my native language but it seems like a `h` is missing.  
Please, someone confirm?
![image](https://github.com/f3d-app/f3d/assets/6069752/adbafe49-45a4-4efe-b316-9049d31af3a9)

2023-07-21 21:41 UTC, Meakk commented on library/src/camera_impl.cxx
> +    cam->ParallelProjectionOff();
```suggestion
  cam->SetParallelProjection(!cam->GetParallelProjection());
```

2023-07-21 21:41 UTC, Meakk commented on library/src/camera_impl.cxx
> +camera& camera_impl::ortoview()
Maybe a better name would be `toggleOrthographic()` or `togglePerspective()` to clearly understand calling it again revert to the original state.

2024-02-20 07:49 UTC, closed without merging

2024-02-20 07:49 UTC, mwestphal commented
superseeded by https://github.com/f3d-app/f3d/pull/1235