Python: Improve testing logic using a testing dir arg
f3d-app/f3d pull request #979
Opened 2023-09-10 08:00 UTC by mwestphal

2023-09-10 08:01 UTC, mwestphal commented
@snoyer @Meakk please review

2023-09-10 09:44 UTC, snoyer commented
Could run Black to add empty lines around the functions in `conftest.py` but otherwise looks good

2023-09-10 17:13 UTC, snoyer commented on python/testing/test_image_compare.py
> +    reference = testingDir + "/baselines/TestPythonCompareWithFile.png"
should be fully pythonized now ;p
```suggestion
    testing_dir = Path(__file__).parent.parent.parent / "testing"
    dataset = f"{testing_dir}/data/cow.vtp"
    reference = f"{testing_dir}/baselines/TestPythonCompareWithFile.png"
```

2023-09-10 18:10 UTC, Meakk requested changes

2023-09-10 18:10 UTC, Meakk commented on python/testing/test_image_compare.py
> +    dataset = f"{testing_dir}/data/cow.vtp"
This string formatting is better, but let's do it for the other test too.

2023-09-11 03:28 UTC, Meakk approved these changes

2023-09-12 05:38 UTC, merged